public enum TipoExame {
    RAIO_X,
    TOMOGRAFIA,
    RESSONANCIA_MAGNETICA,
    ULTRASSOM,
    ELETROCARDIOGRAMA,
    EXAME_SANGUE,
    PRESSAO_ARTERIAL,
    HEMOGRAMA,
    GLICEMIA_JEJUM,
    COLESTEROL_TOTAL,
    URINA_EAS,
    PARASITOLOGICO_FEZES,
    CREATININA,
    TSH,
    T4_LIVRE,
    TRANSAMINASES_ALT_AST,
    HEMOGLOBINA_GLICADA,
    MAMOGRAFIA,
    DENSITOMETRIA_OSSEA,
    ECOCARDIOGRAMA
}

